kind: Ingress
metadata:
  name: resources
spec:
  rules:
  - host: ap-vote-reults.highvail.com
    http:
      paths:
      - backend:
          service:
            name: resources
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ap-vote-reults.highvail.com
    secretName: highvail-tls

